name: CI-CD

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_IMAGE: "${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKERHUB_REPO_NAME }}"
    
jobs:

  ci:
    runs-on: ubuntu-22.04

    if: github.actor != 'github-actions'

    steps:

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven 3.9.5
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        tar -xvzf apache-maven-3.9.5-bin.tar.gz
        sudo mv apache-maven-3.9.5 /opt/maven
        sudo rm -f /usr/bin/mvn
        sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn

    - name: Verify Maven version
      run: mvn -version

    - name: Build jar and Test
      run: |
        mvn -B -DskipTests clean package
        mvn test

    - name: Increment version
      run: |
        current_version=$(grep -o '<version>.*</version>' pom.xml | head -n1 | sed 's/<[^>]*>//g')
        new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1} 1' | sed 's/ /./g')
        echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build --file ./docker/dockerfile --tag ${{ env.DOCKER_IMAGE }} .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Push to DockerHub
      run: |
        docker push ${{ env.DOCKER_IMAGE }}:latest
        docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:${{ env.NEW_VERSION }} 
        docker push ${{ env.DOCKER_IMAGE }}:${{ env.NEW_VERSION }} 

    - name: Update version
      run: |
        git config --local user.email "github-actions"
        git config --local user.name "github-actions"
        sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.NEW_VERSION }}/" pom.xml
        git add pom.xml
        git commit -m "Update version in pom.xml"
        git push




